name: cached_network_image_web
description: Web implementation of CachedNetworkImage
version: 2.0.1
homepage: https://github.com/Baseflow/flutter_cached_network_image

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  cached_network_image_platform_interface: ^5.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.5
  material_ui: ^1.0.0
  web: ^1.0.0

dev_dependencies:
  file: ">=7.0.0 <8.0.0"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_cache_manager:
    git:
      url: git@github.com:glemartret/flutter_cache_manager.git
      path: flutter_cache_manager
      ref: feature/progressive
  cached_network_image_platform_interface:
    git:
      url: git@github.com:glemartret/flutter_cached_network_image.git
      path: cached_network_image_platform_interface
      ref: feature/progressive
