name: cached_network_image_web
description: Web implementation of CachedNetworkImage
version: 2.0.3
homepage: https://github.com/Baseflow/flutter_cached_network_image

environment:
  sdk: ^3.12.0
  flutter: '>=3.44.0'

dependencies:
  cached_network_image_platform_interface: ^5.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.5
  web: ^1.1.1

  material_ui: ^1.3.0
dev_dependencies:
  file: '>=7.0.0 <8.0.0'
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
